# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.
# Project
version=1.3.7
group=com.netcatgirl.immersivethunder
java_version=21
# Common
# Select a file from gradle/minecraft-versions with -Pmc_target=26.1.2.
mc_target=1.21.x
minecraft_version=1.21.11
minecraft_version_label=1.21.x
mod_name=ImmersiveThunder: Reforged
mod_file_name=ImmersiveThunder-Reforged
mod_author=AREKKUZZERA
mod_id=immersivethunder
license=MIT
credits=netcatgirl (original mod creator)
description=Just a simple mod to use distance-based thunder sounds.
minecraft_version_range=[1.21.11, 1.21.11]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.11
parchment_version=2025.12.20
# Fabric
fabric_version=0.141.3+1.21.11
fabric_loader_version=0.19.2
fabric_minecraft_version_range=>=1.21 <26.1
#https://modrinth.com/mod/modmenu/
modmenu_version=17.0.0
#https://modrinth.com/mod/cloth-config/
cloth_config_version=21.11.153
# Forge
forge_version=61.1.5
forge_loader_version_range=[61,)
forge_dependency_version_range=[61.1.5,)
forge_minecraft_version_range=[1.21.11, 1.21.11]
# NeoForge
neoforge_version=21.11.42
neoforge_loader_version_range=[4,)
neoforge_dependency_version_range=[21.11.42,)
neoforge_minecraft_version_range=[1.21.11, 1.21.11]
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.problems.report=false
org.gradle.java.installations.paths=C:/Users/DUMBZZERA/.gradle/jdks/jdk8u482-b08,C:/Program Files/Eclipse Adoptium/jdk-21.0.9.10-hotspot,C:/Program Files/Eclipse Adoptium/jdk-25.0.3.9-hotspot
systemProp.org.gradle.java.installations.paths=C:/Users/DUMBZZERA/.gradle/jdks/jdk8u482-b08,C:/Program Files/Eclipse Adoptium/jdk-21.0.9.10-hotspot,C:/Program Files/Eclipse Adoptium/jdk-25.0.3.9-hotspot
