minecraft_unobfuscated=true
java_version=25
minecraft_version=26.3
minecraft_version_label=26.3
minecraft_version_range=[26.3, 26.3]
fabric_minecraft_version_range=>=26.3 <=26.3
neo_form_version=26.3-1
parchment_minecraft=
parchment_version=
fabric_version=0.162.0+26.3
fabric_loader_version=0.19.5
modmenu_version=
cloth_config_version=
forge_version=
forge_loader_version_range=
forge_dependency_version_range=
forge_minecraft_version_range=
neoforge_version=26.3.0.52-beta
neoforge_loader_version_range=[5,)
neoforge_dependency_version_range=[26.3.0.52-beta,)
neoforge_minecraft_version_range=[26.3, 26.3]
